### PR TITLE
change script injection approach to use a temporary `<script` tag

### LINKED ISSUE #1162: Extension prevents websites (tested on atlassian.com) from loading styles
**Intended outcome:**
I was surfing the web trying to access the Atlassian website [atlassian.com](https://www.atlassian.com/). The website looks like the following when the extension is disabled or removed

Screenshot 2023-12-10 at 09 32 23

**Actual outcome:**
The website loads without styles 

Screenshot 2023-12-10 at 09 50 45

**How to reproduce the issue:**
Install or enable the extension then open  [atlassian.com](https://www.atlassian.com/)

**Desktop (please complete the following information):**

- OS: macOS Sonoma 14.0
- Browser: Arc Version 1.20.1 (43987), Brave v 1.61.101, Microsoft Edge Version 120.0.2210.61
- Extension version: Version 4.2.3

### PR DESCRIPTION
**Pull request by phryneas**
This would potentially fix #1162, #937 and #839 

It's just a temporary fix though, as for Chrome we'll have to switch to manifest v3 soon, but it will be less of a problem there since that allows to inject content scripts into `ExecutionWorld.MAIN`.

### CODE REVIEW

File: src/extension/tab/tab.ts [hunk 1]
```diff
@@ -2,25 +2,33 @@
...
-    const importMap = document.querySelector('script[type="importmap"]');
-    if (importMap != null) {
-      importMap.parentNode?.insertBefore(script, importMap.nextSibling);
-    } else {
-      const head =
-        document.head ||
-        document.getElementsByTagName("head")[0] ||
-        document.documentElement;
-      head.insertBefore(script, head.lastChild);
+  script.textContent = code;
```
Comment (phryneas) [inline src/extension/tab/tab.ts:24]: By retrieving the text and using `textContent`, we can synchronously insert and remove the injected `script` tag with no change of any hydration being confused by it.

**Comment by alessbell** [comment]
Just wondering @phryneas: have you tried building the devtools locally with this fix and testing with sites where we see this issue? No problem if not, I can run the repro in a bit myself.

**Comment by phryneas** [comment]
I've built them using `yarn run firefox` and `yarn run chrome`, and on both cases atlassian.com did load up and `window.__APOLLO_DEVTOOLS_GLOBAL_HOOK__` was correctly initialized.
I also tried Firefox & Chrome on a page that uses Apollo Client and could interact with the DevTools.

**Comment by phryneas** [comment]
@alessbell  I've built them using `yarn run firefox` and `yarn run chrome`, and on both cases atlassian.com did load up and `window.__APOLLO_DEVTOOLS_GLOBAL_HOOK__` was correctly initialized.
I also tried Firefox & Chrome on a page that uses Apollo Client and could interact with the DevTools.

**Comment by alessbell** [comment]
SGTM @phryneas, let's add a changeset and 🚀

**Review by alessbell — APPROVED** [review]
